sudo: false
language: node_js
node_js:
  - 4.1

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=stable
    - BROWSER=firefox BVER=beta

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable

before_script:
  - npm install
  - bower update
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - grunt
  - npm test
